version: '3.7'

services:
  rust-dev:
    image: rust:1.61
    container_name: rust_dev
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: savacan # cargo で必要になる